// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

type Handler_Expecter struct {
	mock *mock.Mock
}

func (_m *Handler) EXPECT() *Handler_Expecter {
	return &Handler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: problem
func (_m *Handler) Handle(problem string) (string, error) {
	ret := _m.Called(problem)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(problem)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(problem)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Handler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type Handler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//  - problem string
func (_e *Handler_Expecter) Handle(problem interface{}) *Handler_Handle_Call {
	return &Handler_Handle_Call{Call: _e.mock.On("Handle", problem)}
}

func (_c *Handler_Handle_Call) Run(run func(problem string)) *Handler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Handler_Handle_Call) Return(_a0 string, _a1 error) *Handler_Handle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func NewHandler() *Handler {
	return &Handler{}
}
