// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// command is an autogenerated mock type for the command type
type command struct {
	mock.Mock
}

type command_Expecter struct {
	mock *mock.Mock
}

func (_m *command) EXPECT() *command_Expecter {
	return &command_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields:
func (_m *command) Execute() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// command_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type command_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *command_Expecter) Execute() *command_Execute_Call {
	return &command_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *command_Execute_Call) Run(run func()) *command_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *command_Execute_Call) Return(_a0 error) *command_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

// Добавлять не обязательно
func NewCommand() *command {
	return &command{}
}
