@startuml
'https://plantuml.com/class-diagram


interface Service {
	+CreateEvent(ctx context.Context, data types.EventHandlerData) : (types.Event, error)
	+UpdateEvent(ctx context.Context, data types.UpdateEventHandlerData) : (types.Event, error)
	+DeleteEvent(ctx context.Context, data types.EventHandlerData) : error
	+EventsForPeriod(ctx context.Context, data types.DateIntervalHandlerData) : ([]types.Event, error)
}

class loggingMiddleware {
    -service: Service
    -logger: *logrus.Logger
    -logDateFormat: string
    +CreateEvent(ctx context.Context, data types.EventHandlerData) : (types.Event, error)
}

class loggingMiddleware implements Service

loggingMiddleware o--> Service

class requestDurationMiddleware {
    -service: Service
    -requestDurationMetric: *prometheus.HistogramVec
    +CreateEvent(ctx context.Context, data types.EventHandlerData) : (types.Event, error)
}

class requestDurationMiddleware implements Service

requestDurationMiddleware o--> Service


@enduml
