// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	os "os"

	mock "github.com/stretchr/testify/mock"
)

// strategy is an autogenerated mock type for the strategy type
type strategy struct {
	mock.Mock
}

// Convert provides a mock function with given fields: file
func (_m *strategy) Convert(file *os.File) {
	_m.Called(file)
}

func NewStrategyMock() *strategy {
	return &strategy{}
}
