// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// command is an autogenerated mock type for the command type
type command struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *command) Execute() {
	_m.Called()
}

func NewCommandMock() *command {
	return &command{}
}
