// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// state is an autogenerated mock type for the state type
type state struct {
	mock.Mock
}

// Complete provides a mock function with given fields:
func (_m *state) Complete() {
	_m.Called()
}

// Delete provides a mock function with given fields:
func (_m *state) Delete() {
	_m.Called()
}

// Publish provides a mock function with given fields:
func (_m *state) Publish() {
	_m.Called()
}

func NewStateMock() *state {
	return &state{}
}
