// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sync "sync"
)

// processor is an autogenerated mock type for the processor type
type processor struct {
	mock.Mock
}

// StartProcessing provides a mock function with given fields: ctx, wg
func (_m *processor) StartProcessing(ctx context.Context, wg *sync.WaitGroup) {
	_m.Called(ctx, wg)
}

func NewProcessor() *processor {
	return &processor{}
}
