// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sync "sync"
)

// responder is an autogenerated mock type for the responder type
type responder struct {
	mock.Mock
}

// StartRespond provides a mock function with given fields: ctx, wg
func (_m *responder) StartRespond(ctx context.Context, wg *sync.WaitGroup) {
	_m.Called(ctx, wg)
}

func NewResponder() *responder {
	return &responder{}
}
